### ISSUE TITLE
Multiple Regex examples

### ISSUE THREAD

**Issue by zethon** [mtimmerm/dfalex#1]
I found this repo through here: https://stackoverflow.com/questions/192957/efficiently-querying-one-string-against-multiple-regexes

I am specifically looking for code where I can define an arbitrary number of regexs (with captures!) and match against a single string with one pass over the string. Even though I'm working in C++, this library looks promising and I would be interested in porting it if it serves my needs.

I am curious if you have any examples where you create an arbitrary number of regexs and match them against a string and process the results? Nothing in the test folder jumps out as that but I'm still looking.

**Comment by mtimmerm** [comment]
StringSearcherTest shows how to use SearchAndReplaceBuilder to search and replace multiple patterns in a string simultaneously.  If you don't to do replacements, you can use a StringSearcher.  SearchAndReplaceBuilder uses one of those so you can look at that code to see how it works.

There are no internal captures in these kinds of patterns (DFA-based rather than PCRE-type), but once you find a match you can always do more processing on it.  Finding the match is the part that needs to be fast.

**Comment by zethon** [comment]
> There are no internal captures in these kinds of patterns (DFA-based rather than PCRE-type), but once you find a match you can always do more processing on it. Finding the match is the part that needs to be fast.

That's more or less what I was thinking. If I can narrow 10k regexs down to one and then run something like `std::regex` with that one... well, two passes over a string are still better than 10k.

I'm assuming this library just implements the basic operators (`+ ? * ( | )`), do you have any thoughts on how easily it would be to extend it to others? Namely `[ ]` and even `^` and `$`. (No backreferences!)

**Comment by mtimmerm** [comment]
It supports character classes [ ].  ^ and $ are not specified in the patterns themselves, but it's quite easy to anchor searches to the beginning and/or end of the string when you call the library.

If you really have 10K regexes to match, then this kind of matcher is the way to do it, since the time required does not depend at all on the number of input expressions or their size.   Searching using std::regex and a very big union expression will not much faster than searching for the 10K regexes individually, because of the way those kinds regexes are implemented.

Porting my library to C++ is not an easy task, though!  Maybe you should try to fit your requirements into something like Flex instead: https://github.com/westes/flex

**Comment by zethon** [comment]
> Porting my library to C++ is not an easy task, though! Maybe you should try to fit your requirements into something like Flex instead: https://github.com/westes/flex

As I understand the goal in general is to take the regexs, convert them into their NFA form, then into DFAs. Once I have that, the time it takes to search more regexs grows linearly. 

Perhaps this is not an easy task but not an impossible task! :) Actually, it looks your library does some things I don't need, such as find-and-replace when really all I need is find-and-capture. I will probably use this as more of a guide.
